### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by samsonsite1** [adang1345/PythonWin7#10]
How can I install PythonWin7 under Anaconda3 (https://www.anaconda.com/) ?

**Comment by samsonsite1** [comment]
I don't know if this is the correct procedure, but this is what I did:

Installed the official version of Python 3.10.6 into Anaconda3:
conda create -n myenv python=3.10.6

then copied the file api-ms-win-core-path-l1-1-0.dll into the Anaconda3 myenv folder.
Is there anything else I must do?

**Comment by adang1345** [comment]
See https://github.com/adang1345/PythonWin7/blob/master/Notes.md for a list of all the changes in the Windows 7 installers, but I think that adding the file `api-ms-win-core-path-l1-1-0.dll` would be all that is necessary to get this working with Anaconda. If you are able to copy this file into the Anaconda environment folder and get Python to run, then that's a good sign that you don't need to do anything further.

**Comment by samsonsite1** [comment]
Thanks!
