### ISSUE TITLE
Python 3.12 challenges

### ISSUE THREAD

**Issue by adang1345** [adang1345/PythonWin7#11]
Note to self: Python 3.12 removes some code for Windows 7. Maybe we can add it back in when building Python 3.12, or maybe it will be too challenging to continue support for Python 3.12 on Windows 7.

https://github.com/python/cpython/issues/102336
https://github.com/python/cpython/issues/102255

**Comment by zooba** [comment]
You'll likely have the best time handling these the way that we have in some cases - by providing implementations for the functions we used to get with GetProcAddress, just matching the prototype. You could even create your own static library with them and include that in the build, which should reduce the amount of modifications to the CPython sources.

**Comment by adang1345** [comment]
It turns out that not many changes are needed to maintain compatibility with Windows 7. https://github.com/adang1345/PythonWin7/blob/master/patches/restore-win7-handling.patch
