### ISSUE TITLE
Upgrade guidance

### ISSUE THREAD

**Issue by Hub-O-Gits** [adang1345/PythonWin7#13]
RE official -> unofficial:
Is it possible to upgrade directly from official Python x64 (e.g. v3.8) to your unofficial x64 package, or is it recommended/necessary to uninstall the official build first?

RE unofficial -> unofficial:
And once a system is using your unofficial packages, can it be upgraded from version to version in the same (inline) way that the official builds can be?

Thank you

**Comment by adang1345** [comment]
Upgrades can occur only across Python micro versions, so you cannot upgrade from Python 3.8 to 3.9. So it is not possible to upgrade from official Python 3.8 to unofficial Python 3.9. However, you can have both of these versions installed side-by-side on the same machine.

The unofficial installers can be upgraded the same way as the official installers across Python micro versions. For example, you can upgrade from unofficial Python 3.9.10 to unofficial Python 3.9.14.
