### ISSUE TITLE
Cannot install or Run 3.9.x or higher versions

### ISSUE THREAD

**Issue by pauloswear** [adang1345/PythonWin7#15]
I can`t run the python version even with modified version provided by this repo. 
Can you help?

With embedd, the dll error ocurrs.

With installer, setup failed screen appears

**Comment by adang1345** [comment]
Check the comments at https://github.com/adang1345/PythonWin7/issues/5 and https://github.com/adang1345/PythonWin7/issues/3 and see whether they help.
