### ISSUE TITLE
How to install via `nuget`?

### ISSUE THREAD

**Issue by StSav012** [adang1345/PythonWin7#16]
Dear devs,

That's an awesome work you do here!

There are `nuget` packages available in the repo. However, I can't do just
```commandline
nuget install "https://github.com/adang1345/PythonWin7/blob/master/3.11.3/python.3.11.3.nupkg"
```

Neither can I add the repo to `nuget` sources:
```commandline
nuget sources add -name "PythonWin7" -source "https://github.com/adang1345/PythonWin7/blob/master/"
```
Well, I can, but without a JSON description of the repo, it doesn't make much sense.

Please add a word or two to the README about how to use the packages and how to make Python auto-updatable.

**Comment by adang1345** [comment]
This repository is just providing the `.nupkg` file. I'm not sure how to install it with the `nuget` command either. If anyone else knows the answer, then feel free to share.

**Comment by adang1345** [comment]
I have found the answer. Go to the directory containing the `.nupkg` file in Command Prompt. Replace `target\installation\directory` with the location where you want the package installed.

For 64-bit Python, run
`nuget install python -Source %cd% -OuputDirectory target\installation\directory`

For 32-bit Python, run
`nuget install pythonx86 -Source %cd% -OuputDirectory target\installation\directory`

**Comment by adang1345** [comment]
I added these instructions to the README.

**Comment by StSav012** [comment]
Thank you so much!
