### ISSUE TITLE
Thanks for making PythonWin7

### ISSUE THREAD

**Issue by Senyu** [adang1345/PythonWin7#2]
First of all, thank you~ (',,-ω-,,)♡
for built some unofficial installers for Python 3.9 and 3.10 that work on Windows 7 since it is no longer in the developers' interest to maintain official support.

I hope you can keep the unofficial versions in the future...

Many programs, games, browsers still work without problems in windows 7... It is sad to see when a dev says it is not supported or puts a lock on the executable to not work.

About the *.dll (api-ms-win-core-path-l1-1-0.dll) I have been using it for a time, as well as the DirectX 12 DLL for windows 7:
https://github.com/microsoft/DirectX-Specs/blob/master/d3d/D3D12onWin7.md

d3d12.dll and d3d11on12.dll extracting the nuget package: https://www.nuget.org/packages/Microsoft.Direct3D.D3D12On7

(Oh and I will close the topic after you see it (or you can close it)

Thanks again ♡ (ɔˆз(ˆ⌣ˆc)

**Comment by adang1345** [comment]
I'm glad these installers are helpful!

**Comment by brostosjoined** [comment]
Thanks once again now Bombsquad game can work on windows 7

**Comment by HackintoshHD** [comment]
Simply +1.
