### ISSUE TITLE
Requires win7

### ISSUE THREAD

**Issue by lynrayy** [adang1345/PythonWin7#20]
I'm already have win7 but it is requires win7, what?
![image](https://github.com/adang1345/PythonWin7/assets/59417884/94201e8f-f5d6-4d0e-aa80-b602f56d75a3)

**Comment by adang1345** [comment]
See whether https://github.com/adang1345/PythonWin7/issues/3#issuecomment-1257099737 helps.

**Comment by adang1345** [comment]
Closing. Feel free to comment if you're still having the same problem after updating your system.
