### ISSUE TITLE
Link to the Windows update is 32 bit only, should specify 64 bit as well

### ISSUE THREAD

**Issue by allanonmage** [adang1345/PythonWin7#27]
The link that you have posted for KB3063858 is for the 32 bit version only.  If you didn't know, Windows updates are either 32 bit or 64 bit only.  They don't get packaged in the same installer.

The 64 bit version of KB3063858 can be found here:

https://www.microsoft.com/en-gb/download/details.aspx?id=47442

**Comment by adang1345** [comment]
Thank you. I added the link for 64-bit Windows.
