### ISSUE TITLE
Notable changes in Python 3.13

### ISSUE THREAD

**Issue by adang1345** [adang1345/PythonWin7#28]
Notes to self for when I start working on Python 3.13 on Windows 7.

`ProcessSnapshot.h` is not available on Windows 7, so `restore-win7-handling.patch` reverts the change that introduced its usage to the `win32_getppid()` function in `posixmodule.c`. https://github.com/python/cpython/commit/be1c808fcad201adc4d5d6cca52ddb24aeb5e367 introduces an alternate implementation that does not require `ProcessSnapshot.h`. It uses deprecated Windows functions and falls back to using `ProcessSnapshot.h` if those functions fail or no longer exist. Modify the patch to use this alternate implementation for Windows 7 and remove the fallback given that Windows 7 is not going to remove the deprecated functions.

https://github.com/python/cpython/commit/1d95451be1f3080904c00cc4c4a6cc519efdf321 adds `GetSystemTimePreciseAsFileTime()`, which is not available on Windows 7.

**Comment by yulk** [comment]
Thanks for you work!

**Comment by adang1345** [comment]
Python 3.13 RC 1 is up at https://github.com/adang1345/PythonWin7/tree/master/3.13.0rc1.

**Comment by adang1345** [comment]
Python 3.13.0 is out.
