### ISSUE TITLE
Which one can support XP？

### ISSUE THREAD

**Issue by angelfish0808** [adang1345/PythonWin7#29]
I am currently researching an old system. Thank you very much for your package. Win7 has been successfully installed to the latest version. May I ask which version of Python XP currently supports? Thank you!

**Comment by adang1345** [comment]
I think you meant to post this under https://github.com/adang1345/PythonWin7, so I have moved it.

According to https://www.python.org/downloads/windows/, Python officially stopped supporting Windows XP after Python 3.4. My packages in this repository are all Python 3.5 and above, so none of them support Windows XP.

**Comment by greenozon** [comment]
@angelfish0808   Python 3.6.15 possible for old system like Windows XP
will it close your needs?

**Comment by angelfish0808** [comment]
@greenozon I tried the python3.6.15 embedded version, and it showed that it was not a valid win32 program.

**Comment by greenozon** [comment]
It is possible to make it alive on old good Windows XP (Sp3)
eg:

![Screenshot from 2024-03-28 16-07-00](https://github.com/adang1345/PythonWin7/assets/765343/a6a5605b-7c6d-4a42-a9c8-2b1393513276)

what option are you looking for 
a) build it up from sources (using the last cygwin env for Win XP)
b) already built binaries

PS what kind of tasks do you solve on your Win XP machines in python?

**Comment by angelfish0808** [comment]
@greenozon When I run the installation package, it shows that it is not supported. I mainly need to do some data analysis on the old machine.
![11](https://github.com/adang1345/PythonWin7/assets/157368558/1edfc388-33c8-402c-975b-42fb579d9efe)

**Comment by greenozon** [comment]
well, I did not wrote I"ve used standard Python installer from official website
Please read my message again..

**Comment by nicolaasjan** [comment]
I have a Python 3.9 mod running on Windows XP (in order to build [yt-dlp](https://github.com/nicolaasjan/yt-dlp/releases/latest/download/yt-dlp_x86_Windows-XP.zip) for the "retro" community.  😉 )

![screenshot_20240606](https://github.com/adang1345/PythonWin7/assets/14093220/d1651c5f-acde-4cb0-80a7-0a6e2a6f500f)


It was created by MSFN member **cmalex** ([see this post](https://msfn.org/board/topic/183741-python-3813-for-windows-xp-sp3/page/2/#comment-1241782)).

```
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version local@2024.06.01 [db50f19d7] (win_x86_exe)
[debug] Python 3.9.13 (CPython x86 32bit) - Windows-XP-5.1.2600-SP3 (OpenSSL 3.1.0-dev )
[debug] exe versions: ffmpeg N-115062-g5bc3b7f-Reino (fdk,setts), ffprobe N-115062-g5bc3b7f-Reino
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
```
