### ISSUE TITLE
Running python-3.10.1-amd64-full.exe on Win7 still says "Setup failed"

### ISSUE THREAD

**Issue by snoop911** [adang1345/PythonWin7#3]
I'm sure it's something on my end, but shouldn't this exe be installable on Windows 7?
![Untitled](https://user-images.githubusercontent.com/27907285/192124210-a99f652f-49ca-4ff3-a9d0-becc6de1bb78.png)

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/192124286-256475e1-91df-4a9e-8a64-29b460f25999.png)

Wild guess.

**Comment by adang1345** [comment]
The installer works on my Windows 7 machine. If you go to the log file, it should give you further details about why the error is happening. I suspect that your machine does not have update KB2533623 installed. You can try updating your machine via Windows Update or going to https://support.microsoft.com/en-us/topic/microsoft-security-advisory-insecure-library-loading-could-allow-remote-code-execution-486ea436-2d47-27e5-6cb9-26ab7230c704.

**Comment by adang1345** [comment]
I believe I have provided the solution, so I'm closing this. Feel free to reopen if you're still having issues.
