### ISSUE TITLE
Error 0xc000007b when precompiling standard library

### ISSUE THREAD

**Issue by Jevil7452** [adang1345/PythonWin7#34]
As the title says.
The OS is Windows 7 updated with UpdatePack7R2, as well as some other updates.
![obraz](https://github.com/user-attachments/assets/31b05e3e-7838-4276-b47e-aa514ebbec15)
Note that this doesn't break Python itself, only the installer has this error.

**Comment by adang1345** [comment]
Can you upload the installer log files? They should be in your `%TEMP%` directory and be named like `Python*.log`.

**Comment by Jevil7452** [comment]
I forgot about it earlier, sorry about that. But here they are:
[logs.zip](https://github.com/user-attachments/files/17447362/logs.zip)

**Comment by adang1345** [comment]
Thanks, I was able to reproduce the issue. I'm working on a fix.
