### ISSUE TITLE
Error 0x80072f7d: Failed attempt to download URL:

### ISSUE THREAD

**Issue by RealYukiSan** [adang1345/PythonWin7#35]
When trying to install both `python-3.13.0-amd64-full.exe` and `python-3.9.0-amd64-full.exe`, I encounter error that seems a network issue (?) but the internet connection seems working fine, tested by `ping google.com` on cmdline.

How do I debug further this issue? I would appreciate if you point me to the right direction, thanks!

The log:
[Python 3.9.0 (64-bit)_20241023192016.log](https://github.com/user-attachments/files/17491149/Python.3.9.0.64-bit._20241023192016.log)

**Comment by RealYukiSan** [comment]
It works like a charm, thank you very much! :)

problem solved, closing the issue.

**Comment by adang1345** [comment]
I have uploaded fixed installers which do not require Internet access if the Universal CRT is not present.
