### ISSUE TITLE
pip report error

### ISSUE THREAD

**Issue by garyLiuxh** [adang1345/PythonWin7#38]
C:\Users\Administrator>ver

Microsoft Windows [version 6.1.7601]

C:\Users\Administrator>pip list
Package Version
------- -------
pip     24.2

C:\Users\Administrator>pip install pandas
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'Prot
ocolError('Connection aborted.', OSError(22, 'parameters error。', None, -2147024809))': /simple/pandas/

**Comment by adang1345** [comment]
Your machine is likely out of date and doesn't support the security protocols that modern websites like PyPI require. Try updating with Windows update.

**Comment by garyLiuxh** [comment]
firstly, thank your response.
when you are free, please give me a more detail teaching  about "Try updating with Windows update".

**Comment by garyLiuxh** [comment]
command:  pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org pandas
now  it is ok .

**Comment by adang1345** [comment]
I'm glad it's working now.
