### ISSUE TITLE
What happened to the Git commit history?

### ISSUE THREAD

**Issue by Darthagnon** [adang1345/PythonWin7#7]
I forked to my own account and cloned locally. Seeing you updated, I looked to update my fork, but [I'm seeing this](https://github.com/Darthagnon/PythonWin7/compare/master...adang1345:PythonWin7:master)

![Fork_mtphL9GStG](https://user-images.githubusercontent.com/20792748/206809976-c6ac46b1-5b6a-43f3-a39b-fbe873010cb3.png)

Not sure how to synchronise or what I should do...

**Comment by adang1345** [comment]
I've been force-pushing every time I make updates. There's not much sense in keeping history for binary files, and I want to prevent the repository from growing too big. You can update a fork by following the instructions at https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream.

**Comment by Darthagnon** [comment]
Thank you for teaching me something valuable about Git!
