### ISSUE TITLE
Request: adding license and who you are :)

### ISSUE THREAD

**Issue by jamesbraza** [adang1345/PythonWin7#8]
Firstly, I would like to thank you for making and actively maintaining PythonWin7 (similar sentiment to https://github.com/adang1345/PythonWin7/issues/2).  Companies in the manufacturing industry tend to use older OS's... many suppliers still distribute Windows 7 by default.

This request is two parts:
- Would you mind adding a brief section to the README saying who you are?  Just for encouraging potential users that you are legit
- Would you mind adding a license to the project?

**Comment by adang1345** [comment]
Done.
