### ISSUE TITLE
PyCharm doesn't support version >= 3.10

### ISSUE THREAD

**Issue by llpj** [adang1345/PythonWin7#9]
On adding interpreter in PyCharm  '[unsupported]'  in red is prefixed to interpreter entry.
PyCharm detects it as Python 3.1 with message "Python 3.1 has reached its end-of-life date and it is no longer supported in PyCharm"

**Comment by adang1345** [comment]
What version of PyCharm are you using? If you're using PyCharm on Windows 7, you're probably using an older version that doesn't support Python 3.10.

**Comment by adang1345** [comment]
Closing, as this is a PyCharm issue and not a problem with this repository.
